namespace SmarcivaZip.Core.SevenZip;

/// <summary>7-Zip の PROPID（NArchive::NHandlerPropID / kpid*）。</summary>
public enum ItemPropId : uint
{
    NoProperty = 0,
    MainSubfile = 1,
    HandlerItemIndex = 2,
    Path = 3,
    Name = 4,
    Extension = 5,
    IsFolder = 6,
    Size = 7,
    PackedSize = 8,
    Attributes = 9,
    CreationTime = 10,
    LastAccessTime = 11,
    LastWriteTime = 12,
    Solid = 13,
    Commented = 14,
    Encrypted = 15,
    SplitBefore = 16,
    SplitAfter = 17,
    DictionarySize = 18,
    Crc = 19,
    Type = 20,
    IsAnti = 21,
    Method = 22,
    HostOS = 23,
    FileSystem = 24,
    User = 25,
    Group = 26,
    Block = 27,
    Comment = 28,
    Position = 29,
    Prefix = 30,
    NumSubDirs = 31,
    NumSubFiles = 32,
    UnpackVersion = 33,
    Volume = 34,
    IsVolume = 35,
    Offset = 36,
    Links = 37,
    NumBlocks = 38,
    NumVolumes = 39,
    TimeType = 40,
    Bit64 = 41,
    BigEndian = 42,
    Cpu = 43,
    PhysicalSize = 44,
    HeadersSize = 45,
    Checksum = 46,
    Characters = 47,
    Va = 48,
    Id = 49,
    ShortName = 50,
    CreatorApp = 51,
    SectorSize = 52,
    PosixAttrib = 53,
    SymLink = 54,
    Error = 55,
    TotalSize = 56,
    FreeSpace = 57,
    ClusterSize = 58,
    VolumeName = 59,
    LocalName = 60,
    Provider = 61,
    NtSecure = 62,
    IsAltStream = 63,
    IsAux = 64,
    IsDeleted = 65,
    IsTree = 66,
    Sha1 = 67,
    Sha256 = 68,
    ErrorType = 69,
    NumErrors = 70,
    ErrorFlags = 71,
    WarningFlags = 72,
    Warning = 73,
    NumStreams = 74,
    NumAltStreams = 75,
    AltStreamsSize = 76,
    VirtualSize = 77,
    UnpackSize = 78,
    TotalPhySize = 79,
    VolumeIndex = 80,
    SubType = 81,
    ShortComment = 82,
    CodePage = 83,
    IsNotArcType = 84,
    PhysicalSizeCantBeDetected = 85,
    ZerosTailIsAllowed = 86,
    TailSize = 87,
    EmbeddedStubSize = 88,
    NtReparse = 89,
    HardLink = 90,
    INode = 91,
    StreamId = 92,
    ReadOnly = 93,
    OutName = 94,
    CopyLink = 95,

    UserDefined = 0x10000
}

/// <summary>7z.dll の GetHandlerProperty2 に渡す PROPID（NArchive::NHandlerPropID）。</summary>
public enum HandlerPropId : uint
{
    Name = 0,
    ClassId = 1,
    Extension = 2,
    AddExtension = 3,
    Update = 4,
    KeepName = 5,
    Signature = 6,
    MultiSignature = 7,
    SignatureOffset = 8,
    AltStreams = 9,
    NtSecure = 10,
    Flags = 11,
    TimeFlags = 12
}

public enum AskMode : int
{
    Extract = 0,
    Test = 1,
    Skip = 2,
    ReadExternal = 3
}

public enum OperationResult : int
{
    Ok = 0,
    UnsupportedMethod = 1,
    DataError = 2,
    CrcError = 3,
    Unavailable = 4,
    UnexpectedEnd = 5,
    DataAfterEnd = 6,
    IsNotArc = 7,
    HeadersError = 8,
    WrongPassword = 9
}

[Flags]
public enum ArchiveFlags : uint
{
    None = 0,
    KeepName = 1 << 0,
    AltStreams = 1 << 1,
    NtSecure = 1 << 2,
    FindSignature = 1 << 3,
    MultiSignature = 1 << 4,
    UseGlobalOffset = 1 << 5,
    StartOpen = 1 << 6,
    PureStartOpen = 1 << 7,
    BackwardOpen = 1 << 8,
    PreArc = 1 << 9,
    SymLinks = 1 << 10,
    HardLinks = 1 << 11,
    ByExtOnlyOpen = 1 << 12,
    HashHandler = 1 << 13,
    CTime = 1 << 14,
    ATime = 1 << 16,
    MTime = 1 << 18
}
